import React, { useRef, useEffect } from 'react';
import { Monitor, Tablet, Phone, RotateCcw, ExternalLink } from 'lucide-react';
import { useState } from 'react';

interface WebsiteRendererProps {
  code: string;
}

// Wraps the generated code in a fully self-contained HTML document
// with inline CSS — NO external CDN so it always renders inside sandbox
function buildSelfContainedHtml(rawCode: string): string {
  // If it's already a complete HTML document
  const isFullDoc = /<html[\s\S]*>/i.test(rawCode) || /<!doctype/i.test(rawCode);

  const baseStyles = `
    <style>
      *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
      html, body { height: 100%; font-family: 'Segoe UI', system-ui, -apple-system, sans-serif; }
      body { background: #0f0f11; color: #e4e4e7; line-height: 1.6; }
      a { color: #10b981; text-decoration: none; }
      a:hover { text-decoration: underline; }
      img { max-width: 100%; height: auto; }
      button { cursor: pointer; font-family: inherit; }
      input, textarea, select { font-family: inherit; }
      ::-webkit-scrollbar { width: 6px; }
      ::-webkit-scrollbar-track { background: transparent; }
      ::-webkit-scrollbar-thumb { background: #3f3f46; border-radius: 9999px; }

      /* Utility classes matching Tailwind-like patterns generated by AI */
      .flex { display: flex; }
      .flex-col { flex-direction: column; }
      .items-center { align-items: center; }
      .justify-center { justify-content: center; }
      .justify-between { justify-content: space-between; }
      .gap-4 { gap: 1rem; }
      .gap-2 { gap: 0.5rem; }
      .gap-6 { gap: 1.5rem; }
      .gap-8 { gap: 2rem; }
      .p-4 { padding: 1rem; }
      .p-6 { padding: 1.5rem; }
      .p-8 { padding: 2rem; }
      .px-4 { padding-left: 1rem; padding-right: 1rem; }
      .px-6 { padding-left: 1.5rem; padding-right: 1.5rem; }
      .px-8 { padding-left: 2rem; padding-right: 2rem; }
      .py-2 { padding-top: 0.5rem; padding-bottom: 0.5rem; }
      .py-3 { padding-top: 0.75rem; padding-bottom: 0.75rem; }
      .py-4 { padding-top: 1rem; padding-bottom: 1rem; }
      .py-16 { padding-top: 4rem; padding-bottom: 4rem; }
      .py-20 { padding-top: 5rem; padding-bottom: 5rem; }
      .mt-4 { margin-top: 1rem; }
      .mt-8 { margin-top: 2rem; }
      .mb-4 { margin-bottom: 1rem; }
      .mb-2 { margin-bottom: 0.5rem; }
      .mx-auto { margin-left: auto; margin-right: auto; }
      .text-center { text-align: center; }
      .text-left { text-align: left; }
      .text-white { color: #ffffff; }
      .text-gray-400 { color: #9ca3af; }
      .text-gray-300 { color: #d1d5db; }
      .text-gray-200 { color: #e5e7eb; }
      .text-green-400 { color: #4ade80; }
      .text-green-500 { color: #22c55e; }
      .text-emerald-400 { color: #34d399; }
      .text-emerald-500 { color: #10b981; }
      .text-purple-400 { color: #c084fc; }
      .text-blue-400 { color: #60a5fa; }
      .text-xl { font-size: 1.25rem; line-height: 1.75rem; }
      .text-2xl { font-size: 1.5rem; line-height: 2rem; }
      .text-3xl { font-size: 1.875rem; line-height: 2.25rem; }
      .text-4xl { font-size: 2.25rem; line-height: 2.5rem; }
      .text-5xl { font-size: 3rem; line-height: 1; }
      .text-sm { font-size: 0.875rem; line-height: 1.25rem; }
      .text-xs { font-size: 0.75rem; line-height: 1rem; }
      .text-lg { font-size: 1.125rem; line-height: 1.75rem; }
      .font-bold { font-weight: 700; }
      .font-semibold { font-weight: 600; }
      .font-medium { font-weight: 500; }
      .font-light { font-weight: 300; }
      .rounded { border-radius: 0.25rem; }
      .rounded-lg { border-radius: 0.5rem; }
      .rounded-xl { border-radius: 0.75rem; }
      .rounded-2xl { border-radius: 1rem; }
      .rounded-full { border-radius: 9999px; }
      .border { border-width: 1px; border-style: solid; }
      .border-gray-700 { border-color: #374151; }
      .border-gray-800 { border-color: #1f2937; }
      .border-emerald-500 { border-color: #10b981; }
      .border-purple-500 { border-color: #a855f7; }
      .bg-gray-900 { background-color: #111827; }
      .bg-gray-800 { background-color: #1f2937; }
      .bg-gray-700 { background-color: #374151; }
      .bg-zinc-900 { background-color: #18181b; }
      .bg-zinc-800 { background-color: #27272a; }
      .bg-black { background-color: #000000; }
      .bg-white { background-color: #ffffff; }
      .bg-emerald-500 { background-color: #10b981; }
      .bg-emerald-600 { background-color: #059669; }
      .bg-purple-500 { background-color: #a855f7; }
      .bg-blue-500 { background-color: #3b82f6; }
      .bg-green-500 { background-color: #22c55e; }
      .shadow { box-shadow: 0 1px 3px rgba(0,0,0,0.3); }
      .shadow-lg { box-shadow: 0 10px 25px rgba(0,0,0,0.5); }
      .shadow-xl { box-shadow: 0 20px 40px rgba(0,0,0,0.6); }
      .w-full { width: 100%; }
      .w-1\/2 { width: 50%; }
      .w-1\/3 { width: 33.333%; }
      .max-w-xl { max-width: 36rem; }
      .max-w-2xl { max-width: 42rem; }
      .max-w-4xl { max-width: 56rem; }
      .max-w-6xl { max-width: 72rem; }
      .max-w-7xl { max-width: 80rem; }
      .container { width: 100%; max-width: 1280px; margin: 0 auto; padding: 0 1rem; }
      .grid { display: grid; }
      .grid-cols-1 { grid-template-columns: repeat(1, 1fr); }
      .grid-cols-2 { grid-template-columns: repeat(2, 1fr); }
      .grid-cols-3 { grid-template-columns: repeat(3, 1fr); }
      .grid-cols-4 { grid-template-columns: repeat(4, 1fr); }
      .col-span-2 { grid-column: span 2; }
      .min-h-screen { min-height: 100vh; }
      .h-full { height: 100%; }
      .h-screen { height: 100vh; }
      .overflow-hidden { overflow: hidden; }
      .overflow-auto { overflow: auto; }
      .relative { position: relative; }
      .absolute { position: absolute; }
      .fixed { position: fixed; }
      .sticky { position: sticky; }
      .top-0 { top: 0; }
      .inset-0 { top: 0; right: 0; bottom: 0; left: 0; }
      .z-10 { z-index: 10; }
      .z-50 { z-index: 50; }
      .opacity-80 { opacity: 0.8; }
      .backdrop-blur { backdrop-filter: blur(8px); }
      .transition { transition: all 0.2s ease; }
      .hover\\:bg-emerald-600:hover { background-color: #059669; }
      .hover\\:bg-gray-700:hover { background-color: #374151; }
      .hover\\:text-white:hover { color: #fff; }
      .hover\\:scale-105:hover { transform: scale(1.05); }
      .list-none { list-style: none; }
      .space-y-4 > * + * { margin-top: 1rem; }
      .space-y-2 > * + * { margin-top: 0.5rem; }
      .space-x-4 > * + * { margin-left: 1rem; }
      .truncate { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
      .whitespace-pre-wrap { white-space: pre-wrap; }
      .break-words { word-break: break-word; }
      .inline-block { display: inline-block; }
      .block { display: block; }
      .hidden { display: none; }
      .aspect-video { aspect-ratio: 16/9; }
      .object-cover { object-fit: cover; }
      .cursor-pointer { cursor: pointer; }
      .select-none { user-select: none; }
      .resize-none { resize: none; }
      .outline-none { outline: none; }
      .focus\\:outline-none:focus { outline: none; }
      .focus\\:ring-2:focus { box-shadow: 0 0 0 2px #10b981; }
      .disabled\\:opacity-50:disabled { opacity: 0.5; }
      @media (min-width: 768px) {
        .md\\:grid-cols-2 { grid-template-columns: repeat(2, 1fr); }
        .md\\:grid-cols-3 { grid-template-columns: repeat(3, 1fr); }
        .md\\:flex { display: flex; }
        .md\\:text-5xl { font-size: 3rem; }
      }
      @media (min-width: 1024px) {
        .lg\\:grid-cols-3 { grid-template-columns: repeat(3, 1fr); }
        .lg\\:grid-cols-4 { grid-template-columns: repeat(4, 1fr); }
      }
    </style>
  `;

  if (isFullDoc) {
    // Inject base styles into existing document's <head>
    if (/<\/head>/i.test(rawCode)) {
      return rawCode.replace(/<\/head>/i, `${baseStyles}</head>`);
    }
    return rawCode;
  }

  // Wrap snippet in a full document
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  ${baseStyles}
</head>
<body>
${rawCode}
</body>
</html>`;
}

export const WebsiteRenderer: React.FC<WebsiteRendererProps> = ({ code }) => {
  const [device, setDevice] = useState<'desktop' | 'tablet' | 'mobile'>('desktop');
  const iframeRef = useRef<HTMLIFrameElement>(null);

  const srcDoc = buildSelfContainedHtml(code);

  // Write content directly via contentDocument to bypass srcDoc re-render flicker
  useEffect(() => {
    const frame = iframeRef.current;
    if (!frame) return;

    const doc = frame.contentDocument || frame.contentWindow?.document;
    if (!doc) return;

    doc.open();
    doc.write(srcDoc);
    doc.close();
  }, [srcDoc]);

  const getWidthClass = () => {
    switch (device) {
      case 'mobile': return 'max-w-sm';
      case 'tablet': return 'max-w-2xl';
      default: return 'w-full';
    }
  };

  const openNewWindow = () => {
    const w = window.open('', '_blank');
    if (w) {
      w.document.write(srcDoc);
      w.document.close();
    }
  };

  return (
    <div className="h-full flex flex-col bg-zinc-950 overflow-hidden">
      {/* Toolbar */}
      <div className="flex items-center justify-between px-4 py-2 border-b border-zinc-900 bg-zinc-900/30 flex-shrink-0 select-none">
        <div className="flex items-center gap-1 bg-zinc-950 p-0.5 rounded-lg border border-zinc-900">
          {(['desktop', 'tablet', 'mobile'] as const).map((d) => {
            const Icon = d === 'desktop' ? Monitor : d === 'tablet' ? Tablet : Phone;
            return (
              <button
                key={d}
                onClick={() => setDevice(d)}
                className={`p-1.5 rounded-md cursor-pointer transition-colors ${device === d ? 'bg-zinc-800 text-white' : 'text-zinc-500 hover:text-zinc-300'}`}
                title={`${d} view`}
              >
                <Icon className="w-3.5 h-3.5" />
              </button>
            );
          })}
        </div>
        <div className="flex items-center gap-1.5">
          <button
            onClick={() => {
              const doc = iframeRef.current?.contentDocument;
              if (doc) { doc.open(); doc.write(srcDoc); doc.close(); }
            }}
            className="p-1.5 rounded-lg hover:bg-zinc-900 text-zinc-400 hover:text-zinc-200 cursor-pointer border border-zinc-900"
            title="Reload"
          >
            <RotateCcw className="w-3.5 h-3.5" />
          </button>
          <button
            onClick={openNewWindow}
            className="p-1.5 rounded-lg hover:bg-zinc-900 text-zinc-400 hover:text-zinc-200 cursor-pointer border border-zinc-900"
            title="Open in new tab"
          >
            <ExternalLink className="w-3.5 h-3.5" />
          </button>
        </div>
      </div>

      {/* Preview Area */}
      <div className="flex-1 flex justify-center bg-zinc-900/30 overflow-auto p-3">
        <div className={`${getWidthClass()} h-full bg-white rounded-xl overflow-hidden shadow-2xl transition-all duration-200 w-full`}>
          <iframe
            ref={iframeRef}
            title="Preview"
            className="w-full h-full border-0"
            sandbox="allow-scripts allow-same-origin allow-forms allow-popups"
          />
        </div>
      </div>
    </div>
  );
};
